### PR TITLE
Update filters

### PR DESCRIPTION
**Pull request by mr-flibble**
Added eset = 800mb updates,
gog = 360mb redists and cache,
origin= 350mb updates,
crashplan = 2gb cache

### CODE REVIEW

**Comment by mr-flibble** [comment]
Samevages from Origin and GOG are in user appdata - those filters are for programdata:

Content is not game related (only program udpates, logs no savegames)
image

**Comment by mr-flibble** [comment]
Samevages from Origin and GOG are in user appdata - those filters are for programdata:

Content is not game related (only program udpates, logs no savegames)
image

**Comment by TheBestPessimist** [comment]
If that's the case, could you please also add yourself to the credits list?:D

https://github.com/TheBestPessimist/duplicacy-utils/blob/master/Credits.md

**Comment by NiJoao** [comment]
Thanks for the contributions!

I have included those in my fork, and added credits to you, and did some extra improvements on the filters file, such as adding a filters_root file.

I don't know if the current pull-request got my recent changes though.
GitHub newbie here...

**Comment by TheBestPessimist** [comment]
Thanks for the filters update!

**Pull request merged**
