### PR TITLE
support multiple scheduled task using systemd

### PR DESCRIPTION
**Pull request by stanly0726**
support multiple schedule to be set simultaneously by adding $scheduledTaskName into service and timer name

### CODE REVIEW

**Comment by TheBestPessimist** [comment]
This looks ok from my first skim. I will check it out properly this week after work.

**Comment by TheBestPessimist** [comment]
I was testing this (finally) and i'm getting this error:
```
PS /a/duplicacy-utils/create-scheduled-tasks> ./create-scheduled-task-linux-systemd.ps1
Invalid unit name "duplicacy-utils-Duplicacy Backup.timer" escaped as "duplicacy-utils-Duplicacy\x20Backup.timer" (maybe you should use systemd-escape?).
Failed to enable unit: Unit file duplicacy-utils-Duplicacy\x20Backup.timer does not exist.
Invalid unit name "duplicacy-utils-Duplicacy Backup.timer" escaped as "duplicacy-utils-Duplicacy\x20Backup.timer" (maybe you should use systemd-escape?).
Failed to start duplicacy-utils-Duplicacy\x20Backup.timer: Unit duplicacy-utils-Duplicacy\x20Backup.timer not found.


 status of the timer:
Invalid unit name "duplicacy-utils-Duplicacy Backup.timer" escaped as "duplicacy-utils-Duplicacy\x20Backup.timer" (maybe you should use systemd-escape?).
Unit duplicacy-utils-Duplicacy\x20Backup.timer could not be found.


 timer runs next @:
Invalid unit name "duplicacy-utils-Duplicacy Backup.timer" escaped as "duplicacy-utils-Duplicacy\x20Backup.timer" (maybe you should use systemd-escape?).
NEXT LEFT LAST PASSED UNIT ACTIVATES

0 timers listed.
Pass --all to see loaded but inactive timers, too.
PS /a/duplicacy-utils/create-scheduled-tasks>
```

do we need to remove all ` ` (space) characters?

**Comment by TheBestPessimist** [comment]
Steps for future me to test quickly:

(pretty sure i missed some stuff here like `duplicacy init`, but whatever)

```

# docker
docker run   --tty   --privileged   --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --name aaa  robertdebock/ubuntu
# in another terminal
docker exec -it aaa sh

# create folders
mkdir a
mkdir b

# install stuff
apt install wget
apt install git
apt install nano
apt install ncdu 

# pwsh
wget https://github.com/PowerShell/PowerShell/releases/download/v7.3.2/powershell_7.3.2-1.deb_amd64.deb
dpkg -i powershell_7.3.2-1.deb_amd64.deb
apt-get install -f

# duplicacy-utils
cd a
git clone https://github.com/stanly0726/duplicacy-utils

# duplicacy 
wget https://github.com/gilbertchen/duplicacy/releases/download/v3.1.0/duplicacy_linux_x64_3.1.0
mv ./duplicacy_linux_x64_3.1.0 z.exe
cd ./duplicacy-utils/create-scheduled-tasks/
./create-scheduled-task-linux-systemd.ps1


```

**Comment by stanly0726** [comment]
this should replace all space in $scheduledTaskName variable, but i can't test it for now
tell me if you find any more bugs😊

**Comment by TheBestPessimist** [comment]
Thanks a lot for the upgrade!

**Pull request merged**
