### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by NiJoao**
Added "machine local" config file;
Added ability to work with a local/default and a "offsite" storage;
Added command to copy to "offsite" storage;
Added vss-timeout options;
Added multi-threaded for all commands;
Added rate-limit for supported commands;
Added script-level retries;
Added GET-URL on success for remote monitoring;
Added success/fail (0/1) return and logging.

### CODE REVIEW

**Comment by myrison** [comment]
Thanks for submitting the changes!  Awesome additions in this update.  I took a quick look and just have one suggestion.  

- Would it be better to allow the user to configure the name of their offsite storage rather than hard-coding it as 'offsite' ? I think you'd just have to change line 140 in backup.ps1 to accomplish this and then add an associated option in the config file.  I'm a coding noob so I don't want to suggest the changes directly, but wanted to at least raise the question to see what you think.

Thanks again!

**Comment by TheBestPessimist** [comment]
Whoa, lots of things added here, thank you very much @NiJoao !

I'm gonna take my time and review this and check all the changes ( since there are **a lot** ).

I don't exactly know the proper Github etiquette so i'm asking this here first: there are a few things which i don't agree with from a first skim over the changes (eg. the process priority and affinity) so how should i continue? => should i merge the PR and make the changes myself (i don't think this is the proper way) or should i comment what i think needs changing and you update this PR (from what i've seen, this is the normal, github way).

**Comment by NiJoao** [comment]
Yeah, sorry, too many changes I've made over time without pushing to
github. I'll try to do it more often.

I'm also a virgin on PR, but I think commenting first leads to a better
discussion and code. No? Of corse at the end you just merge the changes you
want to.

What do you not like about the priority and affinity? The default values,
or the possibility to set them?
The cpu usage of duplicacy is usually very very low, but I don't like to
have sporadic spikes of usage that may cause stutter, and therefore I'm a
big fan of those settings.
I use them with 0x1 and IDLE in my "local config"s.

I'm currently also testing a copy_snapshots function that copies them to
offsite one snapshot/revision at a time or one ID at a time (configurable)
l.
Takes a lot longer then -all, but constantly makes valid states and
therefore a resume is much faster (on broken connections, etc).

Will PR this when it's better tested.
Regards

**Comment by TheBestPessimist** [comment]
@NiJoao could you please fix the 2 files in conflict, so that i can merge this. 
I'll fix the comments myself afterwards.

**Pull request merged**
